tracking-mode: "path_tracking" # path_tracking, path_following

v_max: 0.7  # m/s
w_max: 1.91 # rad/s

# controller: "LQR"        # LQR, DS, GC
type-test  : "fast-sim"  # fast-sim, fast-real, slow-sim, slow-real
dt         : 0.08
route      : "/home/nilton/Desktop/Videos"

type-traj  : "infinite"  # infinite, circle
eta-traj   : 1.25        # amplitud
cycl-traj  : 1           # number of cycles
cent-traj  : [0.0, 0.0, -0.558607]  # center of the trajectory [x, y, theta]

fast-sim:
  - rho-traj: 10    # n_points : 2 * pi * rho * n_cycles / dt

fast-real:
  - rho-traj: 10    # n_points : 2 * pi * rho * n_cycles / dt

slow-sim:
  - rho-traj: 25   # n_points : 2 * pi * rho * n_cycles / dt

slow-real:
  - rho-traj: 25   # n_points : 2 * pi * rho * n_cycles / dt

LQR:
  - Q:
    - [5, 0, 0]
    - [0, 5, 0]
    - [0, 0, 5]

  - R:
    - [1, 0]
    - [0, 1]

DS:
  - type: "disc" # disc, plane, cone, disc-plane , disc-cone, plane-cone, disc-plane-cone

  - disc:
    - radius: 2.2
    - center: 2.2

  - plane:
    - alpha: 0.25
    
  - cone:
    - phi: 0.184799568
    
GC:
  - Cz:
    - [2.236067977, 0, 0]
    - [0, 2.236067977, 0]
    - [0, 0, 1.224744871]
    - [0, 0, 0]
    - [0, 0, 0]

  - Dz:
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [1, 0]
    - [0, 1]